=== cmorenoruiz/cmorenoruiz.github.io/XML/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="datos_empresa"/>
        <xs:element ref="datos_cliente"/>
        <xs:element ref="datos_factura"/>
      </xs:sequence>
      <xs:attribute name="n_fac" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datos_empresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="direccion" type="xs:string"/>
        <xs:element ref="poblacion"/>
        <xs:element name="provincia" type="xs:string"/>
        <xs:element ref="telefono"/>
        <xs:element name="fax" type="xs:string"/>
        <xs:element name="cif" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="poblacion">
    <xs:complexType >
      <xs:simpleContent>
      <xs:extension base ="xs:string">
        <xs:attribute name="cod_postal"  use="required">
        <xs:restriction base="xs:integer">
          <xs:pattern value="[0-9][0-9][0-9][0-9][0-9]"/>
        </xs:restriction>
      </xs:attribute>
      </xs:extension>  
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="telefono">
    <xs:complexType>
      <xs:attribute name="numero" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datos_cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="direccion" type="xs:string"/>
        <xs:element ref="poblacion"/>
        <xs:element name="provincia" type="xs:string"/>
        <xs:element ref="telefono"/>
        <xs:element ref="tipo"/>
        <xs:element name="nif" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="n_cli" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tipo">
    <xs:complexType mixed="true">
       <xs:restriction base="xs:string" default="PF">
        <xs:pattern value="PF|SA|SL|COOP|ORG"/>
    </xs:restriction>
     <xs:attribute name="nacional" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datos_factura">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fecha" type="xs:string"/>
        <xs:element ref="linea" maxOccurs="unbounded"/>
        <xs:element name="base" type="xs:string"/>
        <xs:element name="cuota_iva" type="xs:string"/>
        <xs:element name="total" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="forma_pago" type="xs:string" use="required"/>
      <xs:attribute name="iva" type="xs:string" use="required"/>
      <xs:attribute name="moneda" type="xs:string" use="required"/>
      <xs:attribute name="n_ped" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="linea">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ref" type="xs:string"/>
        <xs:element name="desc" type="xs:string"/>
        <xs:element name="cant" type="xs:string"/>
        <xs:element name="precio" type="xs:string"/>
        <xs:element name="importe" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cmorenoruiz/cmorenoruiz.github.io/XML/factura para esquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura n_fac="f999" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd">
  <datos_empresa>
	<nombre>Equipos Digitales S.L.</nombre>
	<direccion>Av. Valladolid</direccion>
	<poblacion cod_postal="28043">Madrid</poblacion>
	<provincia>Madrid</provincia>
	<telefono/>
	<fax/>
	<cif>Q-9876543</cif>
  </datos_empresa>
  <datos_cliente n_cli="c879">
	<nombre><![CDATA[<p>Dar&iacute;o, Bueno Guti&eacute;rrez</p>]]></nombre>
	<direccion>Av. Oporto n7 4d</direccion>
	<poblacion cod_postal="28043">Madrid</poblacion>
	<provincia>Madrid</provincia>
	<telefono numero="913.336.681"/>
	<tipo nacional="si">PF</tipo>
        <nif>50253634A</nif>
  </datos_cliente>
  <datos_factura n_ped="p731" forma_pago="efectivo" iva="18" moneda="euro">
	<fecha>12-01-2005</fecha>
	<linea>
		<ref>MII93000F/8</ref>
		<desc>MICRO PENTIUM IV 3000MHZ FB800</desc>
		<cant>1</cant>
		<precio>230</precio>
		<importe>266,80</importe>
	</linea>
	<linea>
		<ref>MB8QDIP4</ref>
		<desc>PLACA BASE QDI P4</desc>
		<cant>1</cant>
		<precio>180</precio>
		<importe>208,80</importe>
	</linea>
	<linea>
		<ref>MEDD512M32</ref>
		<desc>DIMM DDR 512MB 3200</desc>
		<cant>2</cant>
		<precio>40</precio>
		<importe>92,80</importe>
	</linea>
	<linea>
		<ref>HD250GSA7</ref>
		<desc>DISCO DURO 250GB S-ATA 7200</desc>
		<cant>4</cant>
		<precio>120</precio>
		<importe>556,80</importe>
	</linea>
	<base>970,00</base>
	<cuota_iva>155,20</cuota_iva>
	<total>1125,20</total>
  </datos_factura>

</factura>
